### ISSUE TITLE
Missing chainLeft

### ISSUE THREAD

**Issue by patrickap** [nythrox/purifree#11]
First of all I have to say this library is great! 

I wanted to ask if you're planning to add `chainLeft` or do I need to implement it with `swap` or something like that?

All the best

**Comment by nythrox** [comment]
Hey @patrickap! Sorry for the late response
I just added chainLeft and published version 1.16.1 on npm

If you know about any other functions that are missing, please do tell me! (if you'd like you can message me here, or on my telegram for a faster response)
I'd also really like to hear about if you're using this package, I didn't know anyone was actually using it 😰

**Comment by patrickap** [comment]
Thank you I will check it out!

I'm using this library for the first time. I like Purify and their API but was missing the possibility to write my code in pointfree style.

Wouldn't it be cool if your work were available directly in Purify? I think you did a very good job here and everyone there should use your pointfree helpers 😃

**Comment by nythrox** [comment]
It really would be awesome to have it directly in Purify, but the creator of the library didn't want it since it uses HKTs to get the pointfree type signature right, and since HKTs aren't native to typescript the implementation is a bit complex and doesn't align with the Core values of purify (neither does pointfree).

I wanted to make this library somehow just an extension on purify, so you can install them separately, but I'm not sure how to do that with npm and also typescript. If you have any ideas feel free to share them 😃
